### ISSUE TITLE
Unknown pbf field type exception

### ISSUE THREAD

**Issue by YShein** [airmap/AirMapSDK-Android#1]
Hello, i have received an mapbox issue from fabric. 
I have reported it to them, but they told me, that it was an issue with tiles
https://github.com/mapbox/mapbox-gl-native/issues/9969
Could you check it, please?

**Comment by cvance** [comment]
Hey @YShein! We'll take a look at this now and get back to you soon. Sorry for the delay!

**Comment by cvance** [comment]
@YShein is there any more information you have regarding this crash? Are you able to reproduce it? If so, how? Is this device you listed the only device you've seen this crash occur on? How often does it occur?

**Comment by YShein** [comment]
@cvance Sorry, it is all info, that i received. I can't reproduce it, it occurred only one time only on that device.
