### ISSUE TITLE
Update to use Mapbox SDK 8.*

### ISSUE THREAD

**Issue by abrbhat** [airmap/AirMapSDK-Android#13]
This SDK still uses Mapbox SDK 5.*. It would be great if it can be upgraded to use Mapbox SDK 8.*

**Comment by walkmn** [comment]
Is there someone alive?

**Comment by vanshg** [comment]
@walkmn @abrbhat We have a new alpha release `4.0.0-alpha.4`. This is using a newer MapBox SDK version
