### ISSUE TITLE
Invalid parsing of AirMapRuleset.class

### ISSUE THREAD

**Issue by zfort-vitalii** [airmap/AirMapSDK-Android#3]
Field summary always empty for class AirMapRuleset. 

Value for this field taken for description key

 ` this.setSummary(Utils.optString(json, "description"));`

but in JSON came short_description.

```
{
  "id": "ukr_notam",
  "name": "UKR NOTAM",
  "short_name": "NOTAM",
  "short_description": "NOTAM rules for Ukraine",
  "selection_type": "required",
  "layers": [
    "notam"
  ],
  "default": false
} 
```

**Comment by f2m2rd** [comment]
Please re-open if you are still having an issue.
